---

#Use this task if you wanna build image localy
#- name: Build drupal image
#  docker_image:
#    build:
#      path: ./
#      nocache: true
#      pull: true
#    name: vladskvortsov/drupal_nginx_no_db
#    tag: latest
#    source: build
#    force_source: true

- name: Deploy drupal container
  docker_container:
    name: drupal
    image: vladskvortsov/drupal_nginx_no_db:latest
    pull: true
    state: started
    restart: yes
    restart_policy: on-failure
    network_mode: drupal-overlay-net
    ports:
      - "80:80"
#    networks:
#      - name: drupal-overlay-net
#        ipv4_address: 172.3.26.1
    links:
      - db
#         aliases:
#          - drupal
#    command: service php8.1-fpm start && service nginx start && sleep infinity
