---
- name: Deploy drupal container
  docker_image:
    build:
      path: ./
      nocache: true
      pull: true
    name: vladskvortsov/drupal
    tag: latest
    source: build
    force_source: true
#    state: started
#    networks:
#      - name: "{{ docker_network }}"
#        ipv4_address: 192.168.88.214
#        links:
#          - "{{ db_alias }}"
#    ports:
#      - "80:80"
