---
- name: Build drupal image
  docker_image:
    build:
      path: ./
      nocache: true
      pull: true
    name: vladskvortsov/drupal_nginx_no_db
    tag: latest
    source: build
    force_source: true

- name: Deploy drupal container
  docker_container:
    name: drupal
    image: vladskvortsov/drupal_nginx_no_db:latest
    state: started
#    restart: yes
    ports:
      - "80:80"
#    networks:
#      - name: "{{ docker_network }}"
#        ipv4_address: 172.26.6.172
    links:
          - "{{ db_alias }}"
#        aliases:
#          - drupal
