---
- name: Init docker swarm
  docker_swarm:
    state: present

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token

- local_action:
    module: copy
    content: "worker_token: {{ worker_token.stdout }}"
    dest: "./group_vars/worker-join-token.yml"

- name: Create overlay network
  docker_network:
    name: drupal-overlay-net
    driver: overlay
    attachable: yes
    ipam_config:
     - subnet: 10.3.0.0/16
       gateway: 10.3.0.1
       iprange: 10.3.0.0/24
       aux_addresses:
         drupal: 10.3.0.3
         db: 10.3.0.4

