---

- name: Add token variable
  ansible.builtin.include_vars:
    file: ./group_vars/worker-join-token.yml

- name: Add workers to the swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ db_public_ip }}"
    join_token: "{{ worker_token }}"
    remote_addrs: [ '{{ web_public_ip }}:2377' ]

- name: Clean token
  file:
    state: absent
    path: ./group_vars/worker-join-token.yml
  delegate_to: localhost
