---

    - name: Set project directory rights
      ansible.builtin.file:
        path: ~/ansible-drupal-deploy/project
        state: directory
        mode: '0766'

    - name: Tear down existing services
      docker_compose:
        project_src: ./project/
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        project_src: ./project/
      register: output

    - debug:
        var: output
