---

- name: Create a volume
  docker_volume:
    name: "{{ docker_volume }}"


- name: Deploy mysql container
  community.docker.docker_container:
        image: mysql/mysql-server:8.0
        name: "{{ db_alias }}"
        state: started
        healthcheck:
         timeout: 5s
        volumes:
          - '{{ docker_volume }}:/var/lib/mysql:rw'
#        restart_policy: always
        network_mode: drupal-overlay-net
#        default_host_ip: 10.3.0.3

#        networks:
#         - name: drupal-overlay-net
#           ipv4_address: 10.3.0.3

        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: '{{ db_root_pass }}'
          MYSQL_DATABASE: '{{ db_name }}'
          MYSQL_USER: '{{ db_user }}'
          MYSQL_PASSWORD: '{{ db_pass }}'
#        command: ["sleep", "infinity"]

