---
   

- name: Create a network
  docker_network:
    name: "{{ docker_network }}"
#    ipv4_address: 172.26.6.172


- name: Create a volume
  docker_volume:
    name: "{{ docker_volume }}"




- name: Deploy mysql container
  docker_container:
        image: mysql:8.0
        name: "{{ db_alias }}"
        state: started
        volumes:
          - '{{ docker_volume }}:/var/lib/mysql:rw'
        restart: true
#        networks:
#          - name: "{{ docker_network }}"
#            ipv4_address: 172.26.6.172
#            aliases:
#              - "{{ db_alias }}"
        env:
          MYSQL_ROOT_PASSWORD: '{{ db_root_pass }}'
          MYSQL_DATABASE: '{{ db_name }}'
          MYSQL_USER: '{{ db_user }}'
          MYSQL_PASSWORD: '{{ db_pass }}'
