---
- name: Deploy mysql container
  docker_container:
        image: mysql:8.0
        name: '{{ db_alias }}'
        state: started
        volumes:
          - '{{ docker_volume }}:/var/lib/mysql:rw'
#       restart: true
        networks:
          - name: "{{ docker_network }}"
#            ipv4_address: 192.168.56.4
            aliases:
              - "{{ db_alias }}"
        env:
          MYSQL_ROOT_PASSWORD: '{{ db_root_pass }}'
          MYSQL_DATABASE: '{{ db_name }}'
          MYSQL_USER: '{{ db_user }}'
          MYSQL_PASSWORD: '{{ db_pass }}'
